<h1>Supprimer un produit</h1>

<form id="form1" method="post">
	<table>
		<tr>
			<td>Id : </td>
			<td><input type="text" id="id" name="id" readonly="true"
					value="<?php echo $this->viewData['item']->id;?>"/>
			</td>
		</tr>
		<tr>
			<td>Catégorie : </td>
			<td>
			<input type="text" id="category" name="category" readonly="true" 
				value="<?php echo $this->viewData['item']->category;?>"/>
			</td>
		</tr>
		
		<tr><td colspan='2'><input type="submit" value= "  Supprimer  " /></td></tr>
	</table>
</form>
<a href="?controller=Categories">Retour</a>
