<h1>Modifier un produit</h1>

<form id="form1" method="post">
	<table>
		<tr>
			<td>Id : </td>
			<td><input type="text" id="id" name="id" readonly="true" disabled
				value="<?php echo $this->viewData['item']->id;?>"/>
			</td>
		</tr>
		<tr>
			<td>Designation : </td>
			<td><input type="text" id="designation" name="designation" 
					value="<?php echo $this->viewData['item']->designation;?>"/>
				<span id="erreur"><?php 
                                                                            $message = array_shift($this->viewData['item']->getAttributErrorMessages('designation'));
                                                                            echo $message;
                                                        ?></span>
			</td>
		</tr>
		<tr>
			<td>Prix Unitaire : </td>
			<td><input type="text" id="price" name="price" 
				value="<?php echo $this->viewData['item']->price;?>"/>(DH)
			<span id="erreur"><?php 
				$message = array_shift($this->viewData['item']->getAttributErrorMessages('price'));
                                                                            echo $message;
			?></span>
		</td>
		</tr>
		<tr>
			<td>Tva : </td>
			<td><input type="text" id="vat" name="vat" 
				value="<?php echo $this->viewData['item']->vat;?>"/>(%)
				<span id="erreur"><?php 
					$message = array_shift($this->viewData['item']->getAttributErrorMessages('vat'));
                                                                            echo $message;
				?></span>
			</td>
		</tr>
		<tr>
			<td>Quantité : </td>
			<td><input type="text" id="quantity" name="quantity" 
				value="<?php echo $this->viewData['item']->quantity;?>"/>
				<span id="erreur"><?php 
					$message = array_shift($this->viewData['item']->getAttributErrorMessages('quantity'));
                                                                            echo $message;
				?></span>
			</td>
		</tr>
		<tr>
                        <td>Catégorie : </td>
                        <td><input type="text" id="category" name="category"  disabled
                            value="<?php echo $this->viewData['parentItem']->category;?>"/>
                        </td>
                    </tr>
		<tr><td colspan='2'><input type="submit" value= "  Modifier  " /></td></tr>
	</table>
</form>
